export type LedgerRow = {
    ledgerId: number;
    name: string;
    ledgerGroupId?: number | null;
    areaId?: number | null;
    shipAddressLine1?: string | null;
    shipAddressLine2?: string | null;
    shipAddressLine3?: string | null;
    shipCityId?: number | null;
    shipPostalCode?: string | null;
    shipOfficePhone?: string | null;
    shipResidencePhone?: string | null;
    shipMobileNumber?: string | null;
    creditLimitNoOfDays?: number | null;
    creditLimitNoOfBills?: number | null;
    taxCalculation?: number | null;
    taxNature?: number | null;
    taxCapitalGoods?: number | null;
    taxRoundOffSales?: number | null;
    taxRoundOffPurchase?: number | null;
    taxFPurchaseLedgerId?: number | null;
    taxFSalesLedgerId?: number | null;
    taxFSalesLedger2Id?: number | null;
    taxAccountsUpdate?: number | null;
    isGenerateBill?: number | null;
    typeOfParty?: string | null;
    isPrintBill?: number | null;
    isTaxApplicable?: number | null;
    isStopGst?: number | null;
    gstStopDate?: string | null;
    intRate?: number | null;
    isTcsApplicable?: number | null;
    alias?: string | null;
    groupName: string;
    addressLine1?: string | null;
    addressLine2?: string | null;
    addressLine3?: string | null;
    address?: string | null;
    cityId?: number | null;
    cityName?: string | null;
    districtId?: number | null;
    districtName?: string | null;
    stateId?: number | null;
    stateName?: string | null;
    countryId?: number | null;
    countryName?: string | null;
    postalCode?: string | null;
    mobileNumber?: string | null;
    officePhone?: string | null;
    residencePhone?: string | null;
    email?: string | null;
    website?: string | null;
    panNumber?: string | null;
    tinNumber?: string | null;
    tinNumber2?: string | null;
    tinNumber3?: string | null;
    tinNumberFrom2?: string | null;
    tinNumberFrom3?: string | null;
    contactPersonsJson?: string | null;
    ledgerSalesTaxesJson?: string | null;
    gstNumber?: string | null;
    taxRate?: string | null;
    taxTypeCode?: number | null;
    isReverseChargeApplicableFlag?: number | null;
    isExportFlag?: number | null;
    openingBalanceAmount?: string | null;
    balanceType?: number | null;
    isActiveFlag?: number | null;
    extraFields?: string | null;
};

export type FieldDefinition = {
    id: number;
    key: string;
    label: string;
    fieldType: string;
    groupName?: string | null;
    orderNo?: number | null;
    required?: boolean | null;
    defaultValue?: string | null;
    options?: string | null;
};

export type FieldDefinitionGroup = {
    groupName: string;
    definitions: FieldDefinition[];
};

export type ContactPersonRow = {
    rowId: string;
    name: string;
    designation: string;
    mobileNumber: string;
    email: string;
};

export type LedgerSalesTaxRow = {
    rowId: string;
    taxName: string;
    gstNumber: string;
    taxRate: string;
    effectiveDate: string;
    isActiveFlag: number;
};

export type ShippingAddressRow = {
    rowId: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    cityId: string;
    postalCode: string;
    officePhone: string;
    residencePhone: string;
    mobileNumber: string;
};

export type SerializedShippingAddress = Omit<ShippingAddressRow, 'rowId'> & {
    cityId: number | null;
};

export type LedgerFormState = {
    name: string;
    ledgerGroupId: string;
    areaId: string;
    shipAddressLine1: string;
    shipAddressLine2: string;
    shipAddressLine3: string;
    shipCityId: string;
    shipPostalCode: string;
    shipOfficePhone: string;
    shipResidencePhone: string;
    shipMobileNumber: string;
    creditLimitNoOfDays: string;
    creditLimitNoOfBills: string;
    taxCalculation: string;
    taxNature: string;
    taxCapitalGoods: string;
    taxRoundOffSales: string;
    taxRoundOffPurchase: string;
    taxFPurchaseLedgerId: string;
    taxFSalesLedgerId: string;
    taxFSalesLedger2Id: string;
    taxAccountsUpdate: string;
    isGenerateBill: number;
    typeOfParty: string;
    isPrintBill: number;
    isTaxApplicable: number;
    isStopGst: number;
    gstStopDate: string;
    intRate: string;
    isTcsApplicable: number;
    alias: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    countryId: string;
    stateId: string;
    districtId: string;
    cityId: string;
    postalCode: string;
    mobileNumber: string;
    officePhone: string;
    residencePhone: string;
    email: string;
    website: string;
    panNumber: string;
    tinNumber: string;
    tinNumber2: string;
    tinNumber3: string;
    tinNumberFrom2: string;
    tinNumberFrom3: string;
    gstNumber: string;
    taxRate: string;
    taxTypeCode: string;
    openingBalanceAmount: string;
    balanceType: number;
    isActiveFlag: number;
    isReverseChargeApplicableFlag: number;
    isExportFlag: number;
    shippingAddresses: ShippingAddressRow[];
    contactPersons: ContactPersonRow[];
    ledgerSalesTaxes: LedgerSalesTaxRow[];
    extraFields: Record<string, any>;
};

export type LedgerDropdownOption = {
    label: string;
    value: string;
};
